print("What is your name?")
name = input()
print("How old are you?")
age = input()
print("Where do you live?")
place = input()

print("Hello", name)
print("Your age is", age)
print("You live in", place)